// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addanimal.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AddanimalRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AddanimalRoot : GPBRootObject
@end

#pragma mark - AddAnimalMessage

typedef GPB_ENUM(AddAnimalMessage_FieldNumber) {
  AddAnimalMessage_FieldNumber_Name = 1,
  AddAnimalMessage_FieldNumber_Bio = 2,
  AddAnimalMessage_FieldNumber_ProfileImage = 3,
};

@interface AddAnimalMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bio;

@property(nonatomic, readwrite, copy, null_resettable) NSData *profileImage;

@end

#pragma mark - AddAnimalResponse

typedef GPB_ENUM(AddAnimalResponse_FieldNumber) {
  AddAnimalResponse_FieldNumber_Success = 1,
};

@interface AddAnimalResponse : GPBMessage

@property(nonatomic, readwrite) BOOL success;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
