AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  addNewPerson:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello
      Runtime: go1.x
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::308138982327:role/service-role/addNewPerson-role-0zugw285'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /addNewPerson
            Method: ANY
